const WEATHER_NOW = "WEATHER_NOW";
const HOURLY_WEATHER = "HOURLY_WEATHER";
const CHECK_FLAG_DAY = "CHECK_FLAG_DAY";
const SAVED_CITIES = "SAVED_CITIES";
const WEEK_WEATHER = "WEEK_WEATHER";
const TEXT_SEARCH_INPUT = "TEXT_SEARCH_INPUT";
const SEARCH_VARIANT = "SEARCH_VARIANT";
const LAT_AND_LONG = "LAT_AND_LONG";
export {
  WEATHER_NOW,
  CHECK_FLAG_DAY,
  WEEK_WEATHER,
  SAVED_CITIES,
  HOURLY_WEATHER,
  TEXT_SEARCH_INPUT,
  SEARCH_VARIANT,
  LAT_AND_LONG,
};
