const WEATHER_NOW = "WEATHER_NOW";
const HOURLY_WEATHER = "HOURLY_WEATHER";
const CHECK_FLAG_DAY = "CHECK_FLAG_DAY";
const SAVED_CITIES = "SAVED_CITIES";
const WEEK_WEATHER = "WEEK_WEATHER";
export {
  WEATHER_NOW,
  CHECK_FLAG_DAY,
  WEEK_WEATHER,
  SAVED_CITIES,
  HOURLY_WEATHER,
};
